(function(){function G(r){function d(a,b){this.value=a;this.sign=b;this.isSmall=!1}function e(a){this.value=a;this.sign=0>a;this.isSmall=!0}function u(a){return-C<a&&a<C}function y(a){return 1E7>a?[a]:1E14>a?[a%1E7,Math.floor(a/1E7)]:[a%1E7,Math.floor(a/1E7)%1E7,Math.floor(a/1E14)]}function A(a){D(a);var b=a.length;if(4>b&&0>B(a,S))switch(b){case 0:return 0;case 1:return a[0];case 2:return a[0]+a[1]*p;default:return a[0]+(a[1]+a[2]*p)*p}return a}function D(a){for(var b=a.length;0===a[--b];);a.length=
b+1}function N(a){for(var b=Array(a),c=-1;++c<a;)b[c]=0;return b}function E(a){return 0<a?Math.floor(a):Math.ceil(a)}function F(a,b){var c=a.length,q=b.length,f=Array(c),d=0,g=p,e,l;for(l=0;l<q;l++)e=a[l]+b[l]+d,d=e>=g?1:0,f[l]=e-d*g;for(;l<c;)e=a[l]+d,d=e===g?1:0,f[l++]=e-d*g;0<d&&f.push(d);return f}function H(a,b){return a.length>=b.length?F(a,b):F(b,a)}function O(a,b){var c=a.length,d=Array(c),f=p,e,g;for(g=0;g<c;g++)e=a[g]-f+b,b=Math.floor(e/f),d[g]=e-b*f,b+=1;for(;0<b;)d[g++]=b%f,b=Math.floor(b/
f);return d}function I(a,b){var c=a.length,d=b.length,f=Array(c),e=0,g=p,h,l;for(h=0;h<d;h++)l=a[h]-e-b[h],0>l?(l+=g,e=1):e=0,f[h]=l;for(h=d;h<c;h++){l=a[h]-e;if(0>l)l+=g;else{f[h++]=l;break}f[h]=l}for(;h<c;h++)f[h]=a[h];D(f);return f}function P(a,b,c){var q=a.length,f=Array(q);b=-b;var k=p,g,h;for(g=0;g<q;g++)h=a[g]+b,b=Math.floor(h/k),h%=k,f[g]=0>h?h+k:h;f=A(f);return"number"===typeof f?(c&&(f=-f),new e(f)):new d(f,c)}function T(a,b){var c=a.length,d=b.length,f=N(c+d),e=p,g,h,l,m;for(l=0;l<c;++l){m=
a[l];for(var n=0;n<d;++n)g=b[n],g=m*g+f[l+n],h=Math.floor(g/e),f[l+n]=g-h*e,f[l+n+1]+=h}D(f);return f}function J(a,b){var c=a.length,d=Array(c),f=p,e=0,g,h;for(h=0;h<c;h++)g=a[h]*b+e,e=Math.floor(g/f),d[h]=g-e*f;for(;0<e;)d[h++]=e%f,e=Math.floor(e/f);return d}function G(a,b){for(var c=[];0<b--;)c.push(0);return c.concat(a)}function Q(a,b){var c=Math.max(a.length,b.length);if(400>=c)return T(a,b);var c=Math.ceil(c/2),d=a.slice(c),f=a.slice(0,c),e=b.slice(c),g=b.slice(0,c),h=Q(f,g),l=Q(d,e),d=Q(H(f,
d),H(g,e)),c=H(H(h,G(I(I(d,h),l),c)),G(l,2*c));D(c);return c}function M(a,b,c){return a<p?new d(J(b,a),c):new d(T(b,y(a)),c)}function V(a){var b=a.length,c=N(b+b),d=p,f,e,g,h;for(g=0;g<b;g++){h=a[g];for(var l=0;l<b;l++)f=a[l],f=h*f+c[g+l],e=Math.floor(f/d),c[g+l]=f-e*d,c[g+l+1]+=e}D(c);return c}function W(a,b){var c=a.length,d=N(c),e=p,k,g;g=0;for(c-=1;0<=c;--c)g=g*e+a[c],k=E(g/b),g-=k*b,d[c]=k|0;return[d,g|0]}function K(a,b){var c,q=n(b),f=a.value;c=q.value;if(0===c)throw Error("Cannot divide by zero");
if(a.isSmall)return q.isSmall?[new e(E(f/c)),new e(f%c)]:[m[0],a];if(q.isSmall){if(1===c)return[a,m[0]];if(-1==c)return[a.negate(),m[0]];c=Math.abs(c);if(c<p)return c=W(f,c),f=A(c[0]),c=c[1],a.sign&&(c=-c),"number"===typeof f?(a.sign!==q.sign&&(f=-f),[new e(f),new e(c)]):[new d(f,a.sign!==q.sign),new e(c)];c=y(c)}var k=B(f,c);if(-1===k)return[m[0],a];if(0===k)return[m[a.sign===q.sign?1:-1],m[0]];if(200>=f.length+c.length){var g=c,h=f.length;c=g.length;var k=p,l=N(g.length),z=g[c-1],w=Math.ceil(k/
(2*z)),f=J(f,w),g=J(g,w),s,t,r,v,u,x;f.length<=h&&f.push(0);g.push(0);z=g[c-1];for(s=h-c;0<=s;s--){h=k-1;f[s+c]!==z&&(h=Math.floor((f[s+c]*k+f[s+c-1])/z));r=t=0;u=g.length;for(v=0;v<u;v++)t+=h*g[v],x=Math.floor(t/k),r+=f[s+v]-(t-x*k),t=x,0>r?(f[s+v]=r+k,r=-1):(f[s+v]=r,r=0);for(;0!==r;){h-=1;for(v=t=0;v<u;v++)t+=f[s+v]-k+g[v],0>t?(f[s+v]=t+k,t=0):(f[s+v]=t,t=1);r+=t}l[s]=h}f=W(f,w)[0];c=[A(l),A(f)]}else{k=f.length;l=c.length;z=[];w=[];for(g=p;k;)if(w.unshift(f[--k]),0>B(w,c))z.push(0);else{h=w.length;
s=w[h-1]*g+w[h-2];t=c[l-1]*g+c[l-2];h>l&&(s=(s+1)*g);h=Math.ceil(s/t);do{s=J(c,h);if(0>=B(s,w))break;h--}while(h);z.push(h);w=I(w,s)}z.reverse();c=[A(z),A(w)]}f=c[0];q=a.sign!==q.sign;c=c[1];k=a.sign;"number"===typeof f?(q&&(f=-f),f=new e(f)):f=new d(f,q);"number"===typeof c?(k&&(c=-c),c=new e(c)):c=new d(c,k);return[f,c]}function B(a,b){if(a.length!==b.length)return a.length>b.length?1:-1;for(var c=a.length-1;0<=c;c--)if(a[c]!==b[c])return a[c]>b[c]?1:-1;return 0}function X(a){a=a.abs();if(a.isUnit())return!1;
if(a.equals(2)||a.equals(3)||a.equals(5))return!0;if(a.isEven()||a.isDivisibleBy(3)||a.isDivisibleBy(5))return!1;if(a.lesser(25))return!0}function Y(a){return("number"===typeof a||"string"===typeof a)&&+Math.abs(a)<=p||a instanceof d&&1>=a.value.length}function U(a,b,c){b=n(b);var d=a.isNegative(),e=b.isNegative(),k=d?a.not():a,g=e?b.not():b;b=[];a=[];for(var h=!1,l=!1;!h||!l;)k.isZero()?(h=!0,b.push(d?1:0)):d?b.push(k.isEven()?1:0):b.push(k.isEven()?0:1),g.isZero()?(l=!0,a.push(e?1:0)):e?a.push(g.isEven()?
1:0):a.push(g.isEven()?0:1),k=k.over(2),g=g.over(2);d=[];for(e=0;e<b.length;e++)d.push(c(b[e],a[e]));for(c=bigInt(d.pop()).negate().times(bigInt(2).pow(d.length));d.length;)c=c.add(bigInt(d.pop()).times(bigInt(2).pow(d.length)));return c}function R(a){a=a.value;a="number"===typeof a?a|Z:a[0]+a[1]*p|ga;return a&-a}function $(a,b){a=n(a);b=n(b);return a.greater(b)?a:b}function aa(a,b){a=n(a);b=n(b);return a.lesser(b)?a:b}function ba(a,b){a=n(a).abs();b=n(b).abs();if(a.equals(b))return a;if(a.isZero())return b;
if(b.isZero())return a;for(var c=m[1],d;a.isEven()&&b.isEven();)d=Math.min(R(a),R(b)),a=a.divide(d),b=b.divide(d),c=c.multiply(d);for(;a.isEven();)a=a.divide(R(a));do{for(;b.isEven();)b=b.divide(R(b));a.greater(b)&&(d=b,b=a,a=d);b=b.subtract(a)}while(!b.isZero());return c.isUnit()?a:a.multiply(c)}function ca(a){a=a.value;"number"===typeof a&&(a=[a]);return 1===a.length&&35>=a[0]?"0123456789abcdefghijklmnopqrstuvwxyz".charAt(a[0]):"<"+a+">"}function da(a,b){b=bigInt(b);if(b.isZero()){if(a.isZero())return"0";
throw Error("Cannot convert nonzero numbers to base 0.");}if(b.equals(-1))return a.isZero()?"0":a.isNegative()?Array(1-a).join("10"):"1"+Array(+a).join("01");var c="";a.isNegative()&&b.isPositive()&&(c="-",a=a.abs());if(b.equals(1))return a.isZero()?"0":c+Array(+a+1).join(1);for(var d=[],e=a,k;e.isNegative()||0<=e.compareAbs(b);)k=e.divmod(b),e=k.quotient,k=k.remainder,k.isNegative()&&(k=b.minus(k).abs(),e=e.next()),d.push(ca(k));d.push(ca(e));return c+d.reverse().join("")}function ea(a){if(u(+a)){var b=
+a;if(b===E(b))return new e(b);throw"Invalid integer: "+a;}(b="-"===a[0])&&(a=a.slice(1));var c=a.split(/e/i);if(2<c.length)throw Error("Invalid integer: "+q.join("e"));if(2===c.length){a=c[1];"+"===a[0]&&(a=a.slice(1));a=+a;if(a!==E(a)||!u(a))throw Error("Invalid integer: "+a+" is not a valid exponent.");var q=c[0],c=q.indexOf(".");0<=c&&(a-=q.length-c-1,q=q.slice(0,c)+q.slice(c+1));if(0>a)throw Error("Cannot include negative exponent part for integers");a=q+=Array(a+1).join("0")}if(!/^([0-9][0-9]*)$/.test(a))throw Error("Invalid integer: "+
a);for(var q=[],c=a.length,f=ha,k=c-f;0<c;)q.push(+a.slice(k,c)),k-=f,0>k&&(k=0),c-=f;D(q);return new d(q,b)}function n(a){return"number"===typeof a?(a=u(a)?new e(a):ea(a.toString()),a):"string"===typeof a?ea(a):a}var p=1E7,ha=7,C=9007199254740992,S=y(C),ia=Math.log(C);d.prototype.add=function(a){a=n(a);if(this.sign!==a.sign)return this.subtract(a.negate());var b=this.value,c=a.value;return a.isSmall?new d(O(b,Math.abs(c)),this.sign):new d(H(b,c),this.sign)};d.prototype.plus=d.prototype.add;e.prototype.add=
function(a){a=n(a);var b=this.value;if(0>b!==a.sign)return this.subtract(a.negate());var c=a.value;if(a.isSmall){if(u(b+c))return new e(b+c);c=y(Math.abs(c))}return new d(O(c,Math.abs(b)),0>b)};e.prototype.plus=e.prototype.add;d.prototype.subtract=function(a){var b=n(a);if(this.sign!==b.sign)return this.add(b.negate());a=this.value;var c=b.value;if(b.isSmall)return P(a,Math.abs(c),this.sign);b=this.sign;0<=B(a,c)?a=I(a,c):(a=I(c,a),b=!b);a=A(a);"number"===typeof a?(b&&(a=-a),a=new e(a)):a=new d(a,
b);return a};d.prototype.minus=d.prototype.subtract;e.prototype.subtract=function(a){a=n(a);var b=this.value;if(0>b!==a.sign)return this.add(a.negate());var c=a.value;return a.isSmall?new e(b-c):P(c,Math.abs(b),0<=b)};e.prototype.minus=e.prototype.subtract;d.prototype.negate=function(){return new d(this.value,!this.sign)};e.prototype.negate=function(){var a=this.sign,b=new e(-this.value);b.sign=!a;return b};d.prototype.abs=function(){return new d(this.value,!1)};e.prototype.abs=function(){return new e(Math.abs(this.value))};
d.prototype.multiply=function(a){var b=n(a);a=this.value;var c=b.value,e=this.sign!==b.sign;if(b.isSmall){if(0===c)return m[0];if(1===c)return this;if(-1===c)return this.negate();b=Math.abs(c);if(b<p)return new d(J(a,b),e);c=y(b)}return 4E3<a.length+c.length?new d(Q(a,c),e):new d(T(a,c),e)};d.prototype.times=d.prototype.multiply;e.prototype._multiplyBySmall=function(a){return u(a.value*this.value)?new e(a.value*this.value):M(Math.abs(a.value),y(Math.abs(this.value)),this.sign!==a.sign)};d.prototype._multiplyBySmall=
function(a){return 0===a.value?m[0]:1===a.value?this:-1===a.value?this.negate():M(Math.abs(a.value),this.value,this.sign!==a.sign)};e.prototype.multiply=function(a){return n(a)._multiplyBySmall(this)};e.prototype.times=e.prototype.multiply;d.prototype.square=function(){return new d(V(this.value),!1)};e.prototype.square=function(){var a=this.value*this.value;return u(a)?new e(a):new d(V(y(Math.abs(this.value))),!1)};d.prototype.divmod=function(a){a=K(this,a);return{quotient:a[0],remainder:a[1]}};e.prototype.divmod=
d.prototype.divmod;d.prototype.divide=function(a){return K(this,a)[0]};e.prototype.over=e.prototype.divide=d.prototype.over=d.prototype.divide;d.prototype.mod=function(a){return K(this,a)[1]};e.prototype.remainder=e.prototype.mod=d.prototype.remainder=d.prototype.mod;d.prototype.pow=function(a){var b=n(a),c=this.value;a=b.value;var d;if(0===a)return m[1];if(0===c)return m[0];if(1===c)return m[1];if(-1===c)return b.isEven()?m[1]:m[-1];if(b.sign)return m[0];if(!b.isSmall)throw Error("The exponent "+
b.toString()+" is too large.");if(this.isSmall&&u(d=Math.pow(c,a)))return new e(E(d));d=this;for(b=m[1];;){a&1&&(b=b.times(d),--a);if(0===a)break;a/=2;d=d.square()}return b};e.prototype.pow=d.prototype.pow;d.prototype.modPow=function(a,b){a=n(a);b=n(b);if(b.isZero())throw Error("Cannot take modPow with modulus 0");for(var c=m[1],d=this.mod(b);a.isPositive();){if(d.isZero())return m[0];a.isOdd()&&(c=c.multiply(d).mod(b));a=a.divide(2);d=d.square().mod(b)}return c};e.prototype.modPow=d.prototype.modPow;
d.prototype.compareAbs=function(a){a=n(a);return a.isSmall?1:B(this.value,a.value)};e.prototype.compareAbs=function(a){a=n(a);var b=Math.abs(this.value),c=a.value;return a.isSmall?(c=Math.abs(c),b===c?0:b>c?1:-1):-1};d.prototype.compare=function(a){if(Infinity===a)return-1;if(-Infinity===a)return 1;a=n(a);return this.sign!==a.sign?a.sign?1:-1:a.isSmall?this.sign?-1:1:B(this.value,a.value)*(this.sign?-1:1)};d.prototype.compareTo=d.prototype.compare;e.prototype.compare=function(a){if(Infinity===a)return-1;
if(-Infinity===a)return 1;a=n(a);var b=this.value,c=a.value;return a.isSmall?b==c?0:b>c?1:-1:0>b!==a.sign?0>b?-1:1:0>b?1:-1};e.prototype.compareTo=e.prototype.compare;d.prototype.equals=function(a){return 0===this.compare(a)};e.prototype.eq=e.prototype.equals=d.prototype.eq=d.prototype.equals;d.prototype.notEquals=function(a){return 0!==this.compare(a)};e.prototype.neq=e.prototype.notEquals=d.prototype.neq=d.prototype.notEquals;d.prototype.greater=function(a){return 0<this.compare(a)};e.prototype.gt=
e.prototype.greater=d.prototype.gt=d.prototype.greater;d.prototype.lesser=function(a){return 0>this.compare(a)};e.prototype.lt=e.prototype.lesser=d.prototype.lt=d.prototype.lesser;d.prototype.greaterOrEquals=function(a){return 0<=this.compare(a)};e.prototype.geq=e.prototype.greaterOrEquals=d.prototype.geq=d.prototype.greaterOrEquals;d.prototype.lesserOrEquals=function(a){return 0>=this.compare(a)};e.prototype.leq=e.prototype.lesserOrEquals=d.prototype.leq=d.prototype.lesserOrEquals;d.prototype.isEven=
function(){return 0===(this.value[0]&1)};e.prototype.isEven=function(){return 0===(this.value&1)};d.prototype.isOdd=function(){return 1===(this.value[0]&1)};e.prototype.isOdd=function(){return 1===(this.value&1)};d.prototype.isPositive=function(){return!this.sign};e.prototype.isPositive=function(){return 0<this.value};d.prototype.isNegative=function(){return this.sign};e.prototype.isNegative=function(){return 0>this.value};d.prototype.isUnit=function(){return!1};e.prototype.isUnit=function(){return 1===
Math.abs(this.value)};d.prototype.isZero=function(){return!1};e.prototype.isZero=function(){return 0===this.value};d.prototype.isDivisibleBy=function(a){a=n(a);var b=a.value;return 0===b?!1:1===b?!0:2===b?this.isEven():this.mod(a).equals(m[0])};e.prototype.isDivisibleBy=d.prototype.isDivisibleBy;d.prototype.isPrime=function(){var a=X(this);if(void 0!==a)return a;for(var a=this.abs(),b=a.prev(),c=[2,3,5,7,11,13,17,19],d=b,e,k,g,h;d.isEven();)d=d.divide(2);for(g=0;g<c.length;g++)if(h=bigInt(c[g]).modPow(d,
a),!h.equals(m[1])&&!h.equals(b)){k=!0;for(e=d;k&&e.lesser(b);e=e.multiply(2))h=h.square().mod(a),h.equals(b)&&(k=!1);if(k)return!1}return!0};e.prototype.isPrime=d.prototype.isPrime;d.prototype.isProbablePrime=function(a){var b=X(this);if(void 0!==b)return b;b=this.abs();a=void 0===a?5:a;for(var c=0;c<a;c++)if(!bigInt.randBetween(2,b.minus(2)).modPow(b.prev(),b).isUnit())return!1;return!0};e.prototype.isProbablePrime=d.prototype.isProbablePrime;d.prototype.next=function(){var a=this.value;return this.sign?
P(a,1,this.sign):new d(O(a,1),this.sign)};e.prototype.next=function(){var a=this.value;return a+1<C?new e(a+1):new d(S,!1)};d.prototype.prev=function(){var a=this.value;return this.sign?new d(O(a,1),!0):P(a,1,this.sign)};e.prototype.prev=function(){var a=this.value;return a-1>-C?new e(a-1):new d(S,!0)};for(var x=[1];x[x.length-1]<=p;)x.push(2*x[x.length-1]);var L=x.length,fa=x[L-1];d.prototype.shiftLeft=function(a){if(!Y(a))throw Error(String(a)+" is too large for shifting.");a=+a;if(0>a)return this.shiftRight(-a);
for(var b=this;a>=L;)b=b.multiply(fa),a-=L-1;return b.multiply(x[a])};e.prototype.shiftLeft=d.prototype.shiftLeft;d.prototype.shiftRight=function(a){var b;if(!Y(a))throw Error(String(a)+" is too large for shifting.");a=+a;if(0>a)return this.shiftLeft(-a);for(b=this;a>=L;){if(b.isZero())return b;b=K(b,fa);b=b[1].isNegative()?b[0].prev():b[0];a-=L-1}b=K(b,x[a]);return b[1].isNegative()?b[0].prev():b[0]};e.prototype.shiftRight=d.prototype.shiftRight;d.prototype.not=function(){return this.negate().prev()};
e.prototype.not=d.prototype.not;d.prototype.and=function(a){return U(this,a,function(a,c){return a&c})};e.prototype.and=d.prototype.and;d.prototype.or=function(a){return U(this,a,function(a,c){return a|c})};e.prototype.or=d.prototype.or;d.prototype.xor=function(a){return U(this,a,function(a,c){return a^c})};e.prototype.xor=d.prototype.xor;var Z=1073741824,ga=(p&-p)*(p&-p)|Z;d.prototype.toString=function(a){void 0===a&&(a=10);if(10!==a)return da(this,a);a=this.value;for(var b=a.length,c=String(a[--b]),
d;0<=--b;)d=String(a[b]),c+="0000000".slice(d.length)+d;return(this.sign?"-":"")+c};e.prototype.toString=function(a){void 0===a&&(a=10);return 10!=a?da(this,a):String(this.value)};d.prototype.valueOf=function(){return+this.toString()};d.prototype.toJSNumber=d.prototype.valueOf;e.prototype.valueOf=function(){return this.value};e.prototype.toJSNumber=e.prototype.valueOf;var m=function(a,b){if("undefined"===typeof a)return m[0];if("undefined"!==typeof b){var c;if(10===+b)c=n(a);else{c=b;var d=m[0],f=
m[1],k=a.length;if(2<=c&&36>=c&&k<=ia/Math.log(c))c=new e(parseInt(a,c));else{c=n(c);var k=[],g,h="-"===a[0];for(g=h?1:0;g<a.length;g++){var l=a[g].toLowerCase(),p=l.charCodeAt(0);if(48<=p&&57>=p)k.push(n(l));else if(97<=p&&122>=p)k.push(n(l.charCodeAt(0)-87));else if("<"===l){l=g;do g++;while(">"!==a[g]);k.push(n(a.slice(l+1,g)))}else throw Error(l+" is not a valid character");}k.reverse();for(g=0;g<k.length;g++)d=d.add(k[g].times(f)),f=f.times(c);c=h?d.negate():d}}return c}return n(a)};for(r=0;1E3>
r;r++)m[r]=new e(r),0<r&&(m[-r]=new e(-r));m.one=m[1];m.zero=m[0];m.minusOne=m[-1];m.max=$;m.min=aa;m.gcd=ba;m.lcm=function(a,b){a=n(a).abs();b=n(b).abs();return a.divide(ba(a,b)).multiply(b)};m.isInstance=function(a){return a instanceof d||a instanceof e};m.randBetween=function(a,b){a=n(a);b=n(b);var c=aa(a,b),m=$(a,b).subtract(c);if(m.isSmall)return c.add(Math.round(Math.random()*m));for(var f=[],k=!0,g=m.value.length-1;0<=g;g--){var h=k?m.value[g]:p,l=E(Math.random()*h);f.unshift(l);l<h&&(k=!1)}f=
A(f);return c.add("number"===typeof f?new e(f):new d(f,!1))};return m}var M=[],F=null;"function"!==typeof define&&("object"===typeof module&&module.exports?F=function(r,d){d(require,module)}:(crosscert=window.crosscert=window.crosscert||{},G(crosscert)));(F||"function"===typeof define)&&(F||define)(["require","module"].concat(M),function(r,d){d.exports=function(d){var u=M.map(function(d){return r(d)}).concat(G);d=d||{};d.defined=d.defined||{};if(d.defined.jsbn)return d.jsbn;d.defined.jsbn=!0;for(var y=
0;y<u.length;++y)u[y](d);return d.jsbn}})})();
