/*
 * JSP generated by Resin Professional 4.0.39 (built Tue, 01 Apr 2014 09:46:53 PDT)
 */

package _jsp._web._admin._main;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.net.URLDecoder;
import java.util.*;
import java.io.*;
import nicelib.db.*;
import nicelib.util.*;
import dao.*;
import procure.common.conf.Startup;
import procure.common.utils.*;

public class _index__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=EUC-KR");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
// \ub85c\uadf8\uc544\uc6c3 \ud6c4 \ub4a4\ub85c\uac00\uae30 \uce90\uc2dc \ubc29\uc9c0 2012.11.1 add by \uc720\uc131\ud6c8
response.setHeader("Pragma", "No-cache");
response.setDateHeader("Expires", 0);
response.setHeader("Cache-Control", "no-Cache");
//-------------------------------------------------------

String docRoot = Startup.conf.getString("nicelib.admin_root");
String webUrl = Config.getWebUrl();
String jndi = Config.getJndi();
String tplRoot = docRoot + "/html";
String dataDir = docRoot + "/data";

Util u = new Util(request, response, out);

if(request.getServerName().equals("nicedocu.com")){//www.\uac00 \ube60\uc9c4 \uac74 \uc6f9 \ubc29\ud654\ubcbd\uc5d0 \ub4f1\ub85d\ub418\uc5b4 \uc788\uc9c0 \uc54a\uc740 \ub3c4\ub9e4\uc778\uc774\ub2e4.
	u.redirect("https://www.nicedocu.com"+u.getThisURI()+"?"+u.getQueryString());
	return;
}

if(request.getServerName().equals("www.nicedocu.com")&&!request.isSecure()){
	if(u.isPost()){
		u.jsError("\ubcf4\uc548\uc744 \uc704\ud574 https\ub85c  \uc811\uadfc \ud558\uc138\uc694.\\n\\nhttp\uc811\uadfc\uc2dc post\ubc29\uc2dd\uc73c\ub85c\ub294 \uc811\uadfc\uc774 \ubd88\uac00\ud569\ub2c8\ub2e4.");
	}else{
		u.redirect(request.getRequestURL().toString().replaceAll("http://", "https://")+"?"+u.getQueryString());
	}
	return;
}


Form f = new Form("form1");
f.setRequest(request);

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);

String jspDir = u.getScriptDir();

Auth auth = new Auth(request, response);
//auth.loginURL = webUrl + "/member/login.jsp?mid=LOGIN";
auth.keyName = "AUTHID094";
if(auth.isValid()) {
	DataSet _auth = new DataSet();
	_auth.addRow();
	_auth.put("_ADMIN_ID", auth.getString("_ADMIN_ID"));
	_auth.put("_ADMIN_NAME", auth.getString("_ADMIN_NAME"));
	_auth.put("_AUTH_CD", auth.getString("_AUTH_CD"));
	_auth.put("_BEFORE_LOGIN_DATE", auth.getString("_BEFORE_LOGIN_DATE"));

	p.setVar("login_block", true);
	p.setVar("_auth", _auth);
} else {
	p.setVar("logo", "main_02.gif");
	p.setVar("login_block", false);
}
p.setVar("_sysdate", u.getTimeString());

p.setVar("realgrid_path", "/cab/realgrid/");

p.setVar("SYS_HTTPHOST", request.getServerName());
p.setVar("SYS_PAGE_URL", request.getRequestURL() + (!"".equals(u.getQueryString()) ? "?" + u.getQueryString() : ""));
p.setVar("webUrl", webUrl);

    out.write(_jsp_string1, 0, _jsp_string1.length);
    
// \uad00\ub9ac\uc790 \ud68c\uc6d0\ubc88\ud638\uc778\uc9c0 \uccb4\ud06c
if (auth.isValid() && auth.getString("_ADMIN_ID").equals("")) {
	out.println("<script type=\"text/javascript\">");
	out.println("  alert('\uc798\ubabb\ub41c \uc811\uadfc\uc785\ub2c8\ub2e4.\\n');");
	out.println("if(opener!=null){");
	out.println("  opener.location.href='/web/admin/index.jsp';");
	out.println("  self.close();");
	out.println("}else{");
	out.println("  location.href='/web/admin/index.jsp';");
	out.println("}");
	out.println("</script>");
	out.close();
}

    out.write(_jsp_string1, 0, _jsp_string1.length);
    
String[] agree_ip = {
		 "112.217.108.98"//\ub098\uc774\uc2a4\ub370\uc774\ud130LG
		,"112.217.108.99"//\ub098\uc774\uc2a4\ub370\uc774\ud130LG
		,"219.240.87.178"//\ub098\uc774\uc2a4\ub370\uc774\ud130SK
		,"219.240.87.179"//\ub098\uc774\uc2a4\ub370\uc774\ud130SK
		,"219.240.87.180"//\ub098\uc774\uc2a4\ub370\uc774\ud130SK
		,"127.0.0.1"//\ub85c\uceec \uac1c\ubc1c
};

String login_ip = request.getRemoteAddr();
/*
if(!login_ip.startsWith("192.168.10")){
	if(!u.inArray(login_ip, agree_ip)){
		out.println("<script>");
		out.println("//alert('\ud5c8\uc6a9\ub418\uc9c0 \uc54a\ub294 IP\uc758 \uc811\uadfc\uc785\ub2c8\ub2e4.\\n\\nIP:"+login_ip+"');");
		out.println("</script>");
		return;
	}
}
*/
if(auth.getString("_ADMIN_ID")!=null&&!auth.getString("_ADMIN_ID").equals("")){
	u.redirect("index2.jsp");
	return;
}

f.addElement("returl", u.request("returl"), "");
f.addElement("txtUserID", null, "hname:'\uc544\uc774\ub514', required:'Y', maxbyte:'20'");
f.addElement("txtPassWD", null, "hname:'\ube44\ubc00\ubc88\ud638', required:'Y'");

if(u.isPost() && f.validate())
{
	DataObject adminDao = new DataObject("tcc_admin");
	DataSet mgr_user = adminDao.find("admin_id='"+f.get("txtUserID")+"' and passwd='"+u.sha256(f.get("txtPassWD"))+"'");
	if(!mgr_user.next()){
		u.jsError("\uc0ac\uc6a9\uc790 \uc815\ubcf4\uac00 \uc874\uc7ac \ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.");
		return;
	}
	DataObject loginLogDao = new DataObject("tcc_login_log");
	String before_login_date = loginLogDao.getOne("select max(log_date) from tcc_login_log where login_id = '"+f.get("txtUserID")+"' ");

	DB db = new DB();
	loginLogDao = new DataObject("tcc_login_log");
	loginLogDao.item("login_id", mgr_user.getString("admin_id"));
	loginLogDao.item("log_date", u.getTimeString());
	db.setCommand(loginLogDao.getInsertQuery(), loginLogDao.record);
	if(!db.executeArray()){
		u.jsError("\ucc98\ub9ac\uc911 \uc624\ub958\uac00 \ubc1c\uc0dd \ud558\uc600\uc2b5\ub2c8\ub2e4");
		return;
	}

	// \uc5b4\ub4dc\ubbfc \uc815\ubcf4 \uc800\uc7a5
	auth.put("_ADMIN_ID", mgr_user.getString("admin_id"));
	auth.put("_ADMIN_NAME", mgr_user.getString("admin_name"));
	auth.put("_AUTH_CD", mgr_user.getString("auth_cd"));
	if(!before_login_date.equals("")) {
		auth.put("_BEFORE_LOGIN_DATE", u.getTimeString("yyyy-MM-dd HH:mm:ss", before_login_date));
	}
	auth.setAuthInfo();

	u.jsReplace(URLDecoder.decode(f.get("returl"), "EUC-KR"));
	return;
}



p.setLayout("default");
//p.setDebug(out);
p.setBody("main.index");
p.display(out);

  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6205146603351083403L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("web/admin/main/index.jsp"), -1103463148510343170L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("web/admin/main/init.jsp"), 1734422231484557868L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("web/admin/init.jsp"), -8117036567350438812L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
  }
}
