var _relay_server_url="https://proxy.cloud-sign.co.kr:37001/relay",crosscert=window.crosscert,messageNumber,sessionID,certList,signature,certR;
function query(b,d){var a,f,g={},c=JSON.parse(b);f=_relay_server_url;void 0!=c.manager&&(f+="/Manager");a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");a.open("POST",f,!0);a.setRequestHeader("Content-Type","application/json;charset=UTF-8");a.onreadystatechange=function(f){4==a.readyState&&(200!=a.status?(g.operation=c.operation,g.messageNumber=c.messageNumber,g.resultCode=33434461,g.resultMessage="unexpected answer from Security Server :"+a.status,d(JSON.stringify(g))):
d(a.responseText))};a.send(b)}
function reqGetCert(b,d){messageNumber=1E3;query(JSON.stringify({messageNumber:messageNumber,sessionID:"",client:"PC",operation:"CREATE_SESSION_PC",userID:b}),function(a){a=JSON.parse(a);"0000"==a.resultCode?(sessionID=a.sessionID,a=a.certList.length,certList=[],a=getCert(a,sessionID,function(a){"0000"==a.resultCode?(certList.push(a.certificate),d(a.resultCode,a.resultMessage,certList,"")):d(a.resultCode,a.resultMessage,"","")})):d(a.resultCode,a.resultMessage,"","")})}
function getCert(b,d,a){for(var f=1;f<b+1;f++)messageNumber+=1,query(JSON.stringify({messageNumber:messageNumber,sessionID:d,client:"PC",certificateIndex:f,operation:"GET_CERTIFICATE"}),function(b){a(JSON.parse(b))})}
function reqGenSign(b,d,a,f,g){messageNumber+=1;query(JSON.stringify({messageNumber:messageNumber,sessionID:sessionID,client:"PC",encPinData:"7JR0Bm57P98fFwMgokZWYA==",operation:"VERIFY_PIN"}),function(c){c=JSON.parse(c);if("0000"==c.resultCode){var e=crosscert.md.algorithms.sha256.create();e.start();e.update(f);e=e.digest();c=crosscert.util.createBuffer();var d=crosscert.util.hexToBytes("0001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF003031300D060960864801650304020105000420");
c.putBytes(d);c.putBytes(e.getBytes());e=crosscert.md.algorithms.sha256.create();e.start();e.update(a);var e=e.digest().getBytes(),h=e.substring(0,16),k=e.substring(16,32),e=crosscert.cipher.algorithms.aes.startEncrypting(h,k);e.update(c.getBytes());e.finish(hashPadding);c=e.output.getBytes();messageNumber+=1;c={messageNumber:messageNumber,sessionID:sessionID,client:"PC",operation:"GENERATE_SIGNATURE",certificateIndex:b,tobeSignedData:crosscert.util.encode64(c),keyLength:2048,mechanism:0};c=query(JSON.stringify(c),
function(a){a=JSON.parse(a);if("0000"==a.resultCode){signature=a.signature;a=crosscert.cipher.algorithms.aes.startDecrypting(h,k);a.update(crosscert.util.createBuffer(crosscert.util.decode64(signature)));a.finish();var c=a.output.toHex();messageNumber+=1;a=query(JSON.stringify({messageNumber:messageNumber,sessionID:sessionID,client:"PC",certificateIndex:b,operation:"GET_CERTIFICATE_R"}),function(a){a=JSON.parse(a);if("0000"==a.resultCode){certR=a.certificateR;var b=crosscert.cipher.algorithms.aes.startDecrypting(h,
k);b.update(crosscert.util.createBuffer(crosscert.util.decode64(certR)));b.finish();b=b.output.toHex();g(a.resultCode,a.resultMessage,c,b)}else g(a.resultCode,a.resultMessage,"","");closeSession()})}else g(a.resultCode,a.resultMessage,"",""),closeSession()})}else g(c.resultCode,c.resultMessage,"",""),closeSession()})}
function closeSession(){messageNumber+=1;query(JSON.stringify({messageNumber:messageNumber,sessionID:sessionID,client:"PC",operation:"CLOSE_SESSION"}),function(b){"0000"==JSON.parse(b).resultCode&&(messageNumber=0)})}function hashPadding(b,d,a){a||(d.putByte(128),b=d.length()==b?0:b-d.length(),d.fillWithByte(0,b));return!0};
