SET DEFINE OFF;
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2020266', 1, '킨텍스', 1, '01', 
    '01');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2020266', 2, '등록업체', 1, '02', 
    '02');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2020277', 1, '갑', 1, '01', 
    '01');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2020277', 2, '을', 1, '02', 
    '02');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2020278', 1, '갑', 1, '01', 
    '01');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2020278', 2, '을', 1, '02', 
    '02');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE, SPOP_TYPE)
 Values
   ('2020352', 1, '판매자', 1, '01', 
    '01', 'C');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE, SPOP_TYPE)
 Values
   ('2020352', 2, '구매자', 2, '02', 
    '02', 'C');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE, SPOP_TYPE)
 Values
   ('2020285', 1, 'SK stoa', 1, '01', 
    '01', 'C');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE, SPOP_TYPE)
 Values
   ('2020285', 2, '협력사', 1, '02', 
    '02', 'C');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2020344', 1, '회사', 1, '01', 
    '01');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2020344', 2, '동의자', 1, '02', 
    '02');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2021171', 1, '갑', 1, '01', 
    '01');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2021171', 2, '을', 1, '02', 
    '02');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2021172', 1, '갑', 1, '01', 
    '01');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2021172', 2, '을', 1, '02', 
    '02');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE, SPOP_TYPE)
 Values
   ('2021232', 1, '홈쇼핑', 1, '01', 
    '01', 'C');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE, SPOP_TYPE)
 Values
   ('2021232', 2, '협력사', 1, '02', 
    '02', 'C');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2022004', 1, '렌탈회사', 1, '01', 
    '01');
Insert into TCB_CONT_SIGN_TEMPLATE
   (TEMPLATE_CD, SIGN_SEQ, SIGNER_NAME, SIGNER_MAX, MEMBER_TYPE, CUST_TYPE)
 Values
   ('2022004', 2, '렌탈이용자', 1, '02', 
    '02');
COMMIT;
