var crosscert=window.crosscert,messageNumber,sessionID,connUserID,relayURL,pktVersion,errormsg="\uc77c\uc2dc\uc801\uc778 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4.\n\uc7a0\uc2dc \ud6c4 \ub2e4\uc2dc \uc2dc\ub3c4\ud574\uc8fc\uc138\uc694.",esdownmsg="[\uc774\uc9c0\uc2f8\uc778] \uc571 \ub2e4\uc6b4\ub85c\ub4dc \ub9c1\ud06c\ub97c \ubb38\uc790\ub85c \ubc1c\uc1a1\ud588\uc2b5\ub2c8\ub2e4.\n\ud734\ub300\ud3f0\uc5d0\uc11c \ud655\uc778\ud574 \uc8fc\uc138\uc694.",csdownmsg="[\ud074\ub77c\uc6b0\ub4dc\uc0ac\uc778] \uc571 \ub2e4\uc6b4\ub85c\ub4dc \ub9c1\ud06c\ub97c \ubb38\uc790\ub85c \ubc1c\uc1a1\ud588\uc2b5\ub2c8\ub2e4.\n\ud734\ub300\ud3f0\uc5d0\uc11c \ud655\uc778\ud574 \uc8fc\uc138\uc694.";
function reqMemberInfo(b,c){doXHRObject(memberURL,JSON.stringify({messageNumber:0,sessionID:"",operation:"REQUEST_MEMBER_INFO",phoneNum:b}),function(a){if(""!=a&&0<a.length)switch(a=JSON.parse(a),a.serviceCode){case "-1":case "0":"-1"==a.serviceCode?c(a.resultCode,a.resultMessage,a.serviceCode):c(a.resultCode,a.resultMessage,a.serviceCode+"|"+a.joinpageInfo);break;case "1":case "2":relayURL=a.serverInfo.url_string,pktVersion=a.serverInfo.pktVersion,c(a.resultCode,a.resultMessage,a.serviceCode)}else a=
createERRResponse(),c(a.resultCode,a.resultMessage,"")})}
function reqGetCert(b,c){var a={};a.siteName=encodeURIComponent("HOMETAX");a.siteURL=encodeURIComponent("http://www.hometax.go.kr");a.purpose=encodeURIComponent("LOGIN");messageNumber=2E3;doXHRObject(relayURL,JSON.stringify({messageNumber:messageNumber,sessionID:"",client:"PC-NX",operation:"CREATE_SESSION_PC",userID:b,version:"1.0",pktVersion:pktVersion,siteInfo:a}),function(a){if(""!=a&&0<a.length){var d=JSON.parse(a);if("0000"==d.resultCode){sessionID=d.sessionID;connUserID=b;a=d.certList.length;
for(var e=[],h=1;h<a+1;h++)messageNumber+=1,e.push(JSON.stringify({messageNumber:messageNumber,sessionID:sessionID,client:"PC-NX",certificateIndex:h,operation:"GET_CERTIFICATE",pktVersion:pktVersion}));doSynchronousLoop(e,[],function(a){c(d.resultCode,d.resultMessage,a)})}else"0021"==d.resultCode?reqGetCert(b,c):c(d.resultCode,d.resultMessage,"")}else d=createERRResponse(),c(d.resultCode,d.resultMessage,"")})}
function reqGetCertR(b,c){var a=crosscert.sha256.create();a.start();a.update(connUserID);var a=a.digest().getBytes(),f=a.substring(0,16),d=a.substring(16,32);messageNumber+=1;doXHRObject(relayURL,JSON.stringify({messageNumber:messageNumber,sessionID:sessionID,client:"PC-NX",certificateIndex:b,operation:"GET_CERTIFICATE_R",pktVersion:pktVersion}),function(a){if(""!=a&&0<a.length){if(a=JSON.parse(a),"0000"==a.resultCode){var b=a.certificateR,g=crosscert.cipher.algorithms.aes.startDecrypting(f,d);g.update(crosscert.util.createBuffer(crosscert.util.decode64(b)));
g.finish(g.tmonetpadding);b=g.output.toHex();b=crosscert.util.encode64(crosscert.util.hexToBytes(b));c(a.resultCode,a.resultMessage,b)}}else a=createERRResponse(),c(a.resultCode,a.resultMessage,"")})}
function reqGenSignNonVerifyPin(b,c,a,f){var d=crosscert.sha256.create();d.start();d.update(c);c=d.digest();d=crosscert.sha256.create();d.start();d.update(connUserID);var d=d.digest().getBytes(),e=d.substring(0,16),h=d.substring(16,32),d=crosscert.util.createBuffer(),g=crosscert.util.hexToBytes("0001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF003031300D060960864801650304020105000420");d.putBytes(g);
d.putBytes(c.getBytes());c=crosscert.cipher.algorithms.aes.startEncrypting(e,h);c.update(d.getBytes());c.finish(doHashPadding);c=c.output.getBytes();messageNumber+=1;b={messageNumber:messageNumber,sessionID:sessionID,client:"PC-NX",operation:"GENERATE_SIGNATURE",certificateIndex:b,tobeSignedData:crosscert.util.encode64(c),keyLength:2048,mechanism:0,pktVersion:pktVersion,checkCRL:a};doXHRObject(relayURL,JSON.stringify(b),function(a){if(""!=a&&0<a.length){a=JSON.parse(a);if("0000"==a.resultCode){var c=
a.signature,d=crosscert.cipher.algorithms.aes.startDecrypting(e,h);d.update(crosscert.util.createBuffer(crosscert.util.decode64(c)));d.finish(d.tmonetpadding);c=d.output.toHex();c=crosscert.util.encode64(crosscert.util.hexToBytes(c));f(a.resultCode,a.resultMessage,c)}else f(a.resultCode,a.resultMessage,"");closeSession()}else a=createERRResponse(),f(a.resultCode,a.resultMessage,"")})}
function reqGenSignMultiNonVerifyPin(b,c,a,f,d){c=parseInt(c);var e=crosscert.sha256.create();e.start();e.update(connUserID);var e=e.digest().getBytes(),h=e.substring(0,16),g=e.substring(16,32),e=[],m;for(m in a){var k=crosscert.sha256.create();k.start();k.update(a[m]);var l=k.digest(),k=crosscert.util.createBuffer();k.putBytes(l.getBytes());l=crosscert.cipher.algorithms.aes.startEncrypting(h,g);l.update(k.getBytes());l.finish(doHashPadding);k=l.output.getBytes();e.push(crosscert.util.encode64(k))}messageNumber+=
1;doXHRObject(relayURL,JSON.stringify({messageNumber:messageNumber,sessionID:sessionID,client:"PC-NX",operation:"GENERATE_SIGNATURE_MULTI",certificateIndex:b,keyLength:2048,mechanism:2,pktVersion:pktVersion,count:c,tobeSignedDataList:e,checkCRL:f}),function(a){if(""!=a&&0<a.length){a=JSON.parse(a);if("0000"==a.resultCode){var c=a.signatureList,b=[],e;for(e in c){var f=crosscert.util.createBuffer(crosscert.util.decode64(c[e])),k=crosscert.cipher.algorithms.aes.startDecrypting(h,g);k.update(f);k.finish(k.tmonetpadding);
f=k.output.getBytes();b.push(crosscert.util.encode64(f))}d(a.resultCode,a.resultMessage,b)}else d(a.resultCode,a.resultMessage,"");closeSession()}else a=createERRResponse(),d(a.resultCode,a.resultMessage,"")})}
function reqVerifyVID(b,c,a){if(0==c.length)alert("\uc8fc\ubbfc\ub4f1\ub85d\ubc88\ud638/\uc0ac\uc5c5\uc790\ub4f1\ub85d\ubc88\ud638\ub97c \uc785\ub825\ud574\uc8fc\uc138\uc694.");else{var f,d,e=crosscert.md.algorithms.sha256.create();e.start();e.update(connUserID);var e=e.digest().getBytes(),h=e.substring(0,16),g=e.substring(16,32);messageNumber+=1;doXHRObject(relayURL,JSON.stringify({messageNumber:messageNumber,sessionID:sessionID,client:"PC-NX",certificateIndex:b,operation:"GET_CERTIFICATE",pktVersion:pktVersion}),
function(e){e=JSON.parse(e);"0000"==e.resultCode&&(f=e.certificate,messageNumber+=1,doXHRObject(relayURL,JSON.stringify({messageNumber:messageNumber,sessionID:sessionID,client:"PC-NX",certificateIndex:b,operation:"GET_CERTIFICATE_R",pktVersion:pktVersion}),function(b){b=JSON.parse(b);if("0000"==b.resultCode){b=b.certificateR;var e=crosscert.cipher.algorithms.aes.startDecrypting(h,g);e.update(crosscert.util.createBuffer(crosscert.util.decode64(b)));e.finish(e.tmonetpadding);d=e.output.toHex();b=crosscert.pki.certificateFromBase64(f);
e=crosscert.util.hexToBytes(d);try{crosscert.pkcs8.verifyVIDForHSM(e,c,b)?a("0000","OK",!0):a("0000","OK",!1)}catch(m){a("0014","FAIL",!1)}}}))})}}function doSynchronousLoop(b,c,a){if(0<b.length){var f=function(a,b,h){doXHRObject(relayURL,a[b],function(g){g=JSON.parse(g);c.push(g.certificate);++b<a.length?f(a,b,h):h(c)})};f(b,0,a)}else a(c)}function doHashPadding(b,c,a){a||(c.putByte(128),b=c.length()==b?0:b-c.length(),c.fillWithByte(0,b));return!0}
function doXHRObject(b,c,a){var f={},d=JSON.parse(c);if(void 0==b)f.operation=d.operation,f.messageNumber=d.messageNumber,f.resultCode="0051",f.resultMessage="Initialization failed, please check server url.",a(JSON.stringify(f));else{var e=createCORSRequest("POST",b);if(!e)throw Error("CORS not supported");e.onload=function(){a(e.responseText)};e.onerror=function(){f.operation=d.operation;f.messageNumber=d.messageNumber;f.resultCode="0052";f.resultMessage="unexpected answer from Security Server :"+
e.status;a(JSON.stringify(f))};e.send(c)}}function createCORSRequest(b,c){var a=new XMLHttpRequest;"withCredentials"in a?(a.open(b,c,!0),a.setRequestHeader("Content-Type","application/json;charset=UTF-8")):"undefined"!=typeof XDomainRequest?(a=new XDomainRequest,a.open(b,c)):a=null;return a}function createERRResponse(){return JSON.parse(JSON.stringify({resultCode:"0053",resultMessage:"empty answer from Security Server"}))}
function closeSession(){messageNumber+=1;doXHRObject(relayURL,JSON.stringify({messageNumber:messageNumber,sessionID:sessionID,client:"PC-NX",operation:"CLOSE_SESSION",pktVersion:pktVersion}),function(b){"0000"==JSON.parse(b).resultCode&&(messageNumber=0)})}
function requestAppDown(b,c){var a;"easysign"==c?a="ES01":"cloudsign"==c&&(a="");doXHRObject(smsURL,JSON.stringify({version:a,messageNumber:0,sessionID:"",operation:"SUBMIT_MEMBER_INFO",phoneNumber:b,joinCode:"11111"}),function(b){"0000"!=JSON.parse(b).resultCode?alert(errormsg):"ES01"==a?alert(esdownmsg):alert(csdownmsg)})};
